### ISSUE TITLE
can't build on vs2019

### ISSUE THREAD

**Issue by xengine-qyt** [phluid61/mk-hpack#1]

**Comment by phluid61** [comment]
@xengine-qyt I don't know anything about vs2019. Do you have any more details about what might be going wrong?

**Comment by xengine-qyt** [comment]
is here:1>D:\ConsoleApplication1\ConsoleApplication1\huffman_codes.inc
(2,22): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax

It seems that VS does not support this syntax?

**Comment by phluid61** [comment]
I believe this error C4567 suggests that you are attempting to compile a C source file as C++. Can you check your compilation settings and ensure you're including a `/Tc` ("compile as C code") switch?
